# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		'We must know. We will know.' 
tagline:	'blog'
description:	'My personal blog.'
url:		http://iodiot.github.io

author:
  name:		'Ignat Grob'
  url:		https://google.com/

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/iodiot
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/iodiot
    desc:	Fork me on github

  - icon:	feed
    url:	http://iodiot.github.io/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	http://iodiot.github.io
    
  - title:	About
    url:	http://iodiot.github.io/about
    
copyright:
  author:	Ignat Grob
  url:		http://iodiot.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
